name : on-push CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: cd ../server; npm i

      - name: Run Prettier
        run: cd ../server; npm run prettier:fix

      - name: Build Project
        run: cd ../server; npm run build --if-present

      # - name: Run tests
      #   run: npm test
